name: Devcast.ma
title: Devcast.ma | Podcast marocain
description: Le Podcast des Dev marocains animé par les Dev marocains 🤓
tags:
  - podcast
  - maroc
  - Developpeur
  - carrière
  - devcast.ma
  - devcast
email: youremail@xyz.com
disqus_username: badrzinoun
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
